spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          binder: kafka
          destination: test-spring-kafka
          group: input-group-1
          content-type: text/plain
        output:
          binder: kafka
          destination: test-spring-kafka
          group: output-group-1
          content-type: application/json